import { describe, expect, it } from "vitest";
import {
  COMPILED_DEFAULT_CONFIGURATION,
  createInMemoryConfigurationSource,
  parseApplicationConfiguration,
  parseConfigurationLayer,
  planConfigurationChange,
  resolveConfiguration,
  type ConfigurationLayer,
} from "../config.js";

const clock = { now: () => new Date("2026-08-02T00:00:00.000Z") };
function layer(kind: ConfigurationLayer["kind"], sourceName: string, settings: Record<string, unknown>, lockedFields: readonly string[] = []): ConfigurationLayer { return parseConfigurationLayer({ schemaVersion: 1, kind, sourceName, lockedFields, settings }); }
const credentialRef = { schemaVersion: 1, type: "named", namespace: "provider", name: "primary", version: "v1", expectedKind: "text", providerInstanceId: "provider-1" };
const endpoint = { endpointId: "ollama-loopback", baseUrl: "http://127.0.0.1:11434", timeoutMs: 30_000 };
const provider = { instanceId: "provider-1", providerId: "local-provider", kind: "inference", enabled: true, locality: "local", credentialRef, endpointId: "ollama-loopback", extensions: [{ namespace: "ollama", schemaVersion: 1, value: { keepAliveMs: 60_000 } }] };
const alias = { alias: "local-default", providerInstanceId: "provider-1", modelId: "model-1" };

export function runConfigurationContractSuite(): void {
  describe("configuration contract", () => {
    it("applies the exact precedence order independent of input order", () => { const layers = [layer("runtime", "runtime override", { preferences: { costPriority: 60 } }), layer("project", "project config", { preferences: { costPriority: 40 } }), layer("system", "system policy", { preferences: { costPriority: 20 } }), layer("environment", "launch override", { preferences: { costPriority: 50 } }), layer("user", "user config", { preferences: { costPriority: 30 } })]; const forward = resolveConfiguration(layers, { clock }); const reverse = resolveConfiguration([...layers].reverse(), { clock }); expect(forward.errors).toEqual([]); expect(forward.configuration?.preferences.costPriority).toBe(60); expect(forward.canonicalJson).toBe(reverse.canonicalJson); expect(forward.audit.fingerprint).toBe(reverse.audit.fingerprint); expect(forward.audit.layerKinds).toEqual(["compiled-defaults", "system", "user", "project", "environment", "runtime"]); });
    it("uses explicit merge-by-id and replace collection behavior", () => { const added = layer("project", "project config", { localModelEndpoints: { mode: "merge-by-id", items: [endpoint] }, providers: { mode: "merge-by-id", items: [provider] }, modelAliases: { mode: "merge-by-id", items: [alias] }, modelPreferences: { mode: "replace", items: [{ role: "planning", aliases: ["local-default"] }] } }); const merged = resolveConfiguration([added], { clock }); expect(merged.errors).toEqual([]); expect(merged.configuration?.providers.map((item) => item.instanceId)).toEqual(["provider-1"]); const replaced = resolveConfiguration([added, layer("runtime", "runtime override", { providers: { mode: "replace", items: [] }, modelAliases: { mode: "replace", items: [] }, modelPreferences: { mode: "replace", items: [] }, routing: { defaultAlias: null, fallbackAliases: [] } })], { clock }); expect(replaced.configuration?.providers).toEqual([]); });
    it("reports field provenance, sensitivity, and safe audit metadata", () => { const resolved = resolveConfiguration([layer("user", "user config", { preferences: { theme: "dark" } }), layer("project", "project config", { localModelEndpoints: { mode: "merge-by-id", items: [endpoint] }, providers: { mode: "merge-by-id", items: [provider] }, modelAliases: { mode: "merge-by-id", items: [alias] } })], { clock }); expect(resolved.provenance.find((item) => item.path === "/preferences/theme")?.sourceName).toBe("user config"); expect(resolved.provenance.find((item) => item.path === "/preferences/locale")?.layer).toBe("compiled-defaults"); expect(resolved.sensitiveFields.some((item) => item.path.includes("credentialRef") && item.classification === "secret-reference")).toBe(true); expect(JSON.stringify(resolved.audit)).not.toContain("primary"); expect(Object.isFrozen(resolved.provenance)).toBe(true); });
    it("preserves item provenance when a later layer merges another identifier", () => { const firstProvider = { ...provider, credentialRef: null }; const secondProvider = { ...firstProvider, instanceId: "provider-2" }; const resolved = resolveConfiguration([layer("system", "system config", { localModelEndpoints: { mode: "merge-by-id", items: [endpoint] }, providers: { mode: "merge-by-id", items: [firstProvider] } }), layer("project", "project config", { providers: { mode: "merge-by-id", items: [secondProvider] } })], { clock }); expect(resolved.errors).toEqual([]); expect(resolved.provenance.find((item) => item.path === "/providers/0/instanceId")?.sourceName).toBe("system config"); expect(resolved.provenance.find((item) => item.path === "/providers/1/instanceId")?.sourceName).toBe("project config"); });
    it("rejects unknown fields, inline secrets, hostile prototypes, unsafe source names, and duplicate layers deterministically", () => { const unknown = resolveConfiguration([{ schemaVersion: 1, kind: "user", sourceName: "user", lockedFields: [], settings: { mystery: true } }], { clock }); expect(unknown.errors[0]?.code).toBe("INVALID_CONFIGURATION"); const secret = resolveConfiguration([{ schemaVersion: 1, kind: "user", sourceName: "user", lockedFields: [], settings: { apiKey: "secret-canary" } }], { clock }); expect(secret.errors[0]?.code).toBe("INLINE_SECRET_FORBIDDEN"); expect(JSON.stringify(secret)).not.toContain("secret-canary"); const hostile = Object.create({ polluted: true }); expect(resolveConfiguration([hostile], { clock }).errors).not.toHaveLength(0); expect(resolveConfiguration([{ schemaVersion: 1, kind: "user", sourceName: "C:\\Users\\secret", lockedFields: [], settings: {} }], { clock }).errors).not.toHaveLength(0); const duplicate = resolveConfiguration([layer("user", "one", {}), layer("user", "two", {})], { clock }); expect(duplicate.errors.map((item) => item.code)).toContain("DUPLICATE_LAYER"); });
    it("prevents lower layers from overriding locked mandatory fields", () => { const result = resolveConfiguration([layer("system", "system policy", { workspace: { allowNetwork: false } }, ["workspace"]), layer("project", "project config", { workspace: { allowNetwork: true } })], { clock }); expect(result.configuration).toBeNull(); expect(result.errors).toEqual([expect.objectContaining({ code: "LOCKED_FIELD_OVERRIDE", sourceName: "project config" })]); });
    it("does not mutate inputs and deeply freezes resolved values", () => { const input = { schemaVersion: 1, kind: "user", sourceName: "user config", lockedFields: [], settings: { preferences: { theme: "dark" } } }; const before = JSON.stringify(input); const result = resolveConfiguration([input], { clock }); expect(JSON.stringify(input)).toBe(before); expect(Object.isFrozen(result.configuration)).toBe(true); expect(Object.isFrozen(result.configuration?.preferences)).toBe(true); expect(() => { (result.configuration!.preferences as { theme: string }).theme = "light"; }).toThrow(); });
    it("classifies live, provider, workspace, application, active-operation, and invalid transitions with redacted summaries", () => { const base = resolveConfiguration([layer("project", "project config", { localModelEndpoints: { mode: "merge-by-id", items: [endpoint] }, providers: { mode: "merge-by-id", items: [provider] }, modelAliases: { mode: "merge-by-id", items: [alias] } })], { clock }).configuration!; const changed = resolveConfiguration([layer("project", "project config", { localModelEndpoints: { mode: "merge-by-id", items: [endpoint] }, providers: { mode: "merge-by-id", items: [{ ...provider, credentialRef: { ...credentialRef, version: "v2" } }] }, modelAliases: { mode: "merge-by-id", items: [alias] }, workspace: { maxWritableFiles: 2_000 }, artifactStore: { maxObjectBytes: 900_000_000 }, routing: { preferLocal: false }, data: { defaultClassification: "public" } })], { clock }).configuration!; const plan = planConfigurationChange(base, changed, { clock, activeOperations: 1 }); expect(plan.requiredActions).toEqual(expect.arrayContaining(["live-reload", "restart-provider", "restart-application", "wait-for-operations", "reject-transition"])); const secretChanges = plan.changes.filter((item) => item.path.includes("credentialRef")); expect(secretChanges.length).toBeGreaterThan(0); expect(JSON.stringify(secretChanges)).not.toContain("v1"); expect(JSON.stringify(secretChanges)).not.toContain("v2"); expect(Object.isFrozen(plan)).toBe(true); });
    it("provides a deterministic in-memory source with a fixed layer kind", () => { const source = createInMemoryConfigurationSource(layer("user", "user config", { preferences: { theme: "dark" } })); expect(source.kind).toBe("user"); expect(source.read().settings.preferences?.theme).toBe("dark"); source.replace(layer("user", "user config 2", { preferences: { theme: "light" } })); expect(source.read().settings.preferences?.theme).toBe("light"); expect(() => source.replace(layer("project", "project config", {}))).toThrowError(expect.objectContaining({ code: "INVALID_CONFIGURATION" })); });
  });
}
