import { describe, expect, it } from "vitest";
import { defaultDataHandlingPolicy, parseModelCapabilities } from "@ai-dev-os/domain";
import { parseProviderDescriptor } from "@ai-dev-os/providers";
import {
  POLICY_ACTIONS,
  createManualPolicyClock,
  parsePolicyRequest,
  parsePolicyRule,
  type ApprovalEvidence,
  type PolicyBroker,
  type PolicyClock,
  type PolicyRequest,
  type PolicyRule,
} from "../policy.js";

export interface PolicyContractHarness {
  readonly broker: PolicyBroker;
  readonly clock: PolicyClock & { advance(ms: number): void };
}
export type PolicyContractFactory = (rules: readonly PolicyRule[], clock: PolicyContractHarness["clock"]) => PolicyBroker;

const TRACE = { traceId: "trace-policy", runId: "run-policy", taskId: "task-policy", taskRunId: "attempt-policy" };
const SCOPE = { projectId: "project-policy", taskId: "task-policy", providerInstanceId: "provider-local", workspaceId: "workspace-policy", operationId: "operation-policy", traceId: "trace-policy" };
const SUBJECT_DIGEST = "a".repeat(64);
const LOCAL_PROVIDER = parseProviderDescriptor({ schemaVersion: 1, providerId: "provider", instanceId: "provider-local", kind: "inference", displayName: "Local", locality: "local", retainsData: false, trainsOnInputs: false, supportedClassifications: ["public", "internal", "proprietary-source", "personal", "secret"], capabilities: { streaming: true, structuredOutput: true, toolCalling: true, imageInput: false, repositoryEditing: false, commandExecution: false, networkAccess: false, resumability: false, cancellation: "guaranteed", deadlineEnforcement: true, usageReporting: true, pricingAvailable: false } });
const CLOUD_PROVIDER = parseProviderDescriptor({ ...LOCAL_PROVIDER, instanceId: "provider-cloud", displayName: "Cloud", locality: "cloud", retainsData: true, trainsOnInputs: false, supportedClassifications: ["public", "internal"] });
const MODEL = parseModelCapabilities({ schemaVersion: 1, providerId: "provider", modelId: "model-policy", contextWindowTokens: 8_192, maxOutputTokens: 2_048, supportsToolUse: true, supportsStructuredOutput: true, supportsVision: false, locality: "local", latencyClass: "fast", codingCapability: 3, reasoningCapability: 3, cost: null });

function rule(id: string, input: Partial<PolicyRule>): PolicyRule {
  return parsePolicyRule({ schemaVersion: 1, id, authority: "organization", effect: "allow", actions: POLICY_ACTIONS, classifications: [], risks: [], requiredTransformations: [], approval: null, requiredLocality: "any", forbidInputLogging: false, forbidOutputLogging: false, forbidArtifactPersistence: false, forbidRetention: false, maxRetentionDays: null, forbiddenCapabilities: [], ...input });
}
function request(input: Partial<PolicyRequest> = {}): PolicyRequest {
  const classification = input.classification ?? "public";
  return parsePolicyRequest({ schemaVersion: 1, action: "workspace-read", classification, handlingPolicy: input.handlingPolicy ?? defaultDataHandlingPolicy(classification), risk: "low", locality: "local", provider: LOCAL_PROVIDER, model: MODEL, scope: SCOPE, subjectDigest: SUBJECT_DIGEST, requestedCapabilities: [], transformationsApplied: [], approvalEvidence: [], retentionDays: null, trace: TRACE, requesterKind: "user", ...input });
}
function evidence(requirement: ReturnType<PolicyBroker["evaluate"]>["requiredApprovals"][number], input: Partial<ApprovalEvidence> = {}): ApprovalEvidence {
  return { approvalRequestId: requirement.approvalRequestId, action: requirement.action, risk: requirement.risk, scope: requirement.scope, subjectDigest: requirement.subjectDigest, usage: requirement.usage, approverClass: requirement.approverClass, approverIdentityRef: "identity-user", result: "approved", decidedAt: input.expiresAt === undefined ? "2026-08-02T00:00:00.000Z" : "2026-07-31T00:00:00.000Z", expiresAt: "2026-08-02T00:10:00.000Z", revokedAt: null, consumedAt: null, evidenceRef: "evidence-policy", ...input };
}

export function runPolicyBrokerContractSuite(factory: PolicyContractFactory): void {
  describe("central policy broker contract", () => {
    function setup(extra: readonly PolicyRule[] = []): PolicyContractHarness { const clock = createManualPolicyClock(); return { clock, broker: factory([rule("allow-baseline", {}), ...extra], clock) }; }

    it("allows an explicitly permitted cloud disclosure", () => { const { broker } = setup(); expect(broker.evaluate(request({ action: "provider-disclosure", locality: "cloud", provider: CLOUD_PROVIDER, model: null, scope: { ...SCOPE, providerInstanceId: "provider-cloud" } })).outcome).toBe("allowed"); });
    it("denies cloud disclosure when Stage 2 handling policy forbids it", () => { const { broker } = setup(); const decision = broker.evaluate(request({ action: "provider-disclosure", classification: "secret", handlingPolicy: defaultDataHandlingPolicy("secret"), locality: "cloud", provider: CLOUD_PROVIDER, model: null, scope: { ...SCOPE, providerInstanceId: "provider-cloud" } })); expect(decision.outcome).toBe("denied"); expect(decision.reasons.map((item) => item.code)).toContain("CLOUD_DISCLOSURE_FORBIDDEN"); });
    it("requires local execution and applied redaction deterministically", () => { const local = rule("local-redact", { actions: ["secret-access"], effect: "conditional", requiredLocality: "local", requiredTransformations: ["secrets"] }); const { broker } = setup([local]); const pending = broker.evaluate(request({ action: "secret-access", locality: "unspecified", model: null })); expect(pending.outcome).toBe("conditional"); expect(pending.requiredTransformations).toEqual(["secrets"]); const allowed = broker.evaluate(request({ action: "secret-access", locality: "local", model: null, transformationsApplied: ["secrets"] })); expect(allowed.outcome).toBe("allowed"); });
    it("requires structured approval and accepts applicable evidence", () => { const approval = rule("approval-command", { actions: ["command-execution"], effect: "conditional", approval: { approverClass: "user", usage: "one-shot", ttlMs: 600_000 } }); const { broker } = setup([approval]); const pending = broker.evaluate(request({ action: "command-execution", model: null })); expect(pending.outcome).toBe("conditional"); const approved = broker.evaluate(request({ action: "command-execution", model: null, approvalEvidence: [evidence(pending.requiredApprovals[0]!)] })); expect(approved.outcome).toBe("allowed"); expect(approved.approvalsToConsume).toEqual([pending.requiredApprovals[0]!.approvalRequestId]); });
    it("rejects expired, revoked, mismatched, consumed, denied, and model-supplied approval evidence", () => { const approval = rule("approval-write", { actions: ["workspace-write"], effect: "conditional", approval: { approverClass: "project-owner", usage: "one-shot", ttlMs: 600_000 } }); const { broker } = setup([approval]); const pending = broker.evaluate(request({ action: "workspace-write", risk: "high", model: null })); const requirement = pending.requiredApprovals[0]!; const variants: ApprovalEvidence[] = [evidence(requirement, { approverClass: "project-owner", expiresAt: "2026-08-01T00:00:00.000Z" }), evidence(requirement, { approverClass: "project-owner", revokedAt: "2026-08-02T00:00:01.000Z" }), evidence(requirement, { approverClass: "project-owner", scope: { ...SCOPE, projectId: "different" } }), evidence(requirement, { approverClass: "project-owner", subjectDigest: "b".repeat(64) }), evidence(requirement, { approverClass: "project-owner", consumedAt: "2026-08-02T00:00:01.000Z" })]; for (const item of variants) expect(broker.evaluate(request({ action: "workspace-write", risk: "high", model: null, approvalEvidence: [item] })).outcome).toBe("conditional"); expect(broker.evaluate(request({ action: "workspace-write", risk: "high", model: null, approvalEvidence: [evidence(requirement, { approverClass: "project-owner", result: "denied" })] })).outcome).toBe("denied"); expect(broker.evaluate(request({ action: "workspace-write", risk: "high", model: null, requesterKind: "model", approvalEvidence: [evidence(requirement, { approverClass: "project-owner" })] })).outcome).toBe("conditional"); });
    it("supports reusable approval evidence without consumption", () => { const approval = rule("approval-export", { actions: ["export"], approval: { approverClass: "user", usage: "reusable", ttlMs: 600_000 } }); const { broker } = setup([approval]); const pending = broker.evaluate(request({ action: "export", model: null })); const approved = broker.evaluate(request({ action: "export", model: null, approvalEvidence: [evidence(pending.requiredApprovals[0]!, { usage: "reusable" })] })); expect(approved.outcome).toBe("allowed"); expect(approved.approvalsToConsume).toEqual([]); });
    it("denies capability mismatches and explicit restrictive rules", () => { const deny = rule("deny-network", { authority: "project", effect: "deny", actions: ["network-access"] }); const { broker } = setup([deny]); expect(broker.evaluate(request({ action: "network-access", requestedCapabilities: ["network-access"], model: null })).outcome).toBe("denied"); expect(broker.evaluate(request({ action: "model-eligibility", requestedCapabilities: ["image-input"] })).outcome).toBe("denied"); });
    it("applies explicit command, network, and tool restrictions", () => { const restrictions = [rule("deny-command", { effect: "deny", actions: ["command-execution"] }), rule("deny-network", { effect: "deny", actions: ["network-access"] }), rule("deny-tool", { effect: "deny", actions: ["tool-invocation"] })]; const { broker } = setup(restrictions); for (const action of ["command-execution", "network-access", "tool-invocation"] as const) expect(broker.evaluate(request({ action, model: null, requestedCapabilities: [] })).outcome).toBe("denied"); });
    it("binds derived approval identifiers to action, risk, scope, trace, and normalized-subject digest", () => { const approval = rule("approval-multi", { actions: ["command-execution", "workspace-write"], effect: "conditional", approval: { approverClass: "user", usage: "one-shot", ttlMs: 600_000 } }); const { broker } = setup([approval]); const first = broker.evaluate(request({ action: "command-execution", model: null })).requiredApprovals[0]!; const changedAction = broker.evaluate(request({ action: "workspace-write", model: null })).requiredApprovals[0]!; const changedRisk = broker.evaluate(request({ action: "command-execution", risk: "high", model: null })).requiredApprovals[0]!; const changedScope = broker.evaluate(request({ action: "command-execution", model: null, scope: { ...SCOPE, workspaceId: "other-workspace" } })).requiredApprovals[0]!; const changedSubject = broker.evaluate(request({ action: "command-execution", model: null, subjectDigest: "b".repeat(64) })).requiredApprovals[0]!; expect(new Set([first.approvalRequestId, changedAction.approvalRequestId, changedRisk.approvalRequestId, changedScope.approvalRequestId, changedSubject.approvalRequestId]).size).toBe(5); expect(broker.evaluate(request({ action: "command-execution", model: null, subjectDigest: null })).reasons.map((item) => item.code)).toContain("APPROVAL_SUBJECT_REQUIRED"); });
    it("enforces persistence, logging, retention, export, and deletion policy", () => { const restrict = rule("restrict-output", { actions: ["output-logging", "retention"], forbidOutputLogging: true, maxRetentionDays: 7 }); const { broker } = setup([restrict]); expect(broker.evaluate(request({ action: "artifact-persistence", classification: "secret", handlingPolicy: defaultDataHandlingPolicy("secret"), model: null })).outcome).toBe("denied"); expect(broker.evaluate(request({ action: "input-logging", classification: "personal", handlingPolicy: defaultDataHandlingPolicy("personal"), model: null })).outcome).toBe("denied"); expect(broker.evaluate(request({ action: "output-logging", model: null })).outcome).toBe("denied"); expect(broker.evaluate(request({ action: "retention", retentionDays: 30, model: null })).outcome).toBe("denied"); expect(broker.evaluate(request({ action: "export", model: null })).outcome).toBe("allowed"); expect(broker.evaluate(request({ action: "deletion", model: null })).outcome).toBe("allowed"); });
    it("produces insertion-order-independent fingerprints and deeply frozen decisions", () => { const { broker } = setup(); const a = broker.evaluate(request({ requestedCapabilities: ["streaming", "tool-calling"] })); const reordered = { requesterKind: "user", trace: TRACE, retentionDays: null, approvalEvidence: [], transformationsApplied: [], requestedCapabilities: ["tool-calling", "streaming"], subjectDigest: SUBJECT_DIGEST, scope: SCOPE, model: MODEL, provider: LOCAL_PROVIDER, locality: "local", risk: "low", handlingPolicy: defaultDataHandlingPolicy("public"), classification: "public", action: "workspace-read", schemaVersion: 1 }; const b = broker.evaluate(parsePolicyRequest(reordered)); expect(a.fingerprint).toBe(b.fingerprint); expect(Object.isFrozen(a)).toBe(true); expect(Object.isFrozen(a.audit)).toBe(true); expect(Object.isFrozen(a.reasons)).toBe(true); });
    it("orders matched rules stably", () => { const { broker } = setup([rule("z-project", { authority: "project" }), rule("a-organization", { authority: "organization" }), rule("a-user", { authority: "user" })]); expect(broker.evaluate(request()).matchedRuleIds).toEqual(["a-organization", "allow-baseline", "z-project", "a-user"]); });
  });
}
