export {
  CONFIG_SCHEMA_VERSION,
  CONFIG_LAYER_KINDS,
  COLLECTION_MERGE_MODES,
  CONFIG_LOCK_FIELDS,
  CHANGE_CLASSIFICATIONS,
  CHANGE_ACTIONS,
  ConfigError,
  COMPILED_DEFAULT_CONFIGURATION,
  parseApplicationConfiguration,
  parseConfigurationLayer,
  resolveConfiguration,
  planConfigurationChange,
  createInMemoryConfigurationSource,
  type ConfigLayerKind,
  type CollectionMergeMode,
  type ConfigLockField,
  type ConfigExtension,
  type ProviderInstanceConfiguration,
  type LocalModelEndpoint,
  type ModelAlias,
  type ModelPreference,
  type ApplicationConfiguration,
  type ConfigurationLayer,
  type ConfigurationIssue,
  type ConfigurationProvenance,
  type ConfigurationResolution,
  type ConfigurationClock,
  type InMemoryConfigurationSource,
  type ChangeClassification,
  type ChangeAction,
  type ConfigurationChange,
  type ConfigurationChangePlan,
} from "./config.js";
