export {
  REPOSITORY_INDEX_ERROR_CODES,
  INDEX_DIAGNOSTIC_CODES,
  RepositoryIndexError,
  diagnostic,
  indexFailure,
  failed,
  ok,
  type FailureDetailValue,
  type FailureDetails,
  type IndexDiagnostic,
  type IndexDiagnosticCode,
  type RepositoryIndexErrorCode,
  type RepositoryIndexFailure,
  type RepositoryIndexResult,
} from "./errors.js";

export {
  FILESYSTEM_CASE_SENSITIVITIES,
  SNAPSHOT_ENTRY_KINDS,
  UNICODE_PATH_FORMS,
  type CancellationSignal,
  type FilesystemCaseSensitivity,
  type FilesystemSemantics,
  type IndexClock,
  type SnapshotEntry,
  type SnapshotEntryKind,
  type SnapshotIdentity,
  type SnapshotReadPort,
  type SourceRevision,
  type UnicodePathForm,
} from "./read-port.js";

export {
  MAX_REPOSITORY_PATH_DEPTH,
  MAX_REPOSITORY_PATH_LENGTH,
  MAX_REPOSITORY_SEGMENT_LENGTH,
  PATH_REJECTION_REASONS,
  ancestorDirectories,
  canonicalizeRepositoryPath,
  comparePaths,
  pathBaseName,
  pathDirName,
  pathExtension,
  type PathCanonicalization,
  type PathRejectionReason,
} from "./paths.js";

export {
  DEFAULT_EXCLUSION_RULES,
  DEFAULT_REPOSITORY_INDEX_CONFIGURATION,
  DEFAULT_REPOSITORY_INDEX_LIMITS,
  REPOSITORY_INDEX_ALGORITHM_VERSIONS,
  REPOSITORY_INDEX_CONFIG_SCHEMA_VERSION,
  isExcludedPath,
  parseRepositoryIndexConfiguration,
  repositoryIndexConfigurationFingerprint,
  withRepositoryIndexOverrides,
  type ExclusionRules,
  type RepositoryIndexAlgorithmVersions,
  type RepositoryIndexConfiguration,
  type RepositoryIndexLimits,
} from "./config.js";

export {
  BINARY_EVIDENCE,
  BINARY_SNIFF_BYTES,
  CLASSIFICATION_EVIDENCE,
  CONTENT_ENCODINGS,
  GENERATED_EVIDENCE,
  LANGUAGE_IDS,
  MAX_ORDINARY_AVERAGE_LINE_LENGTH,
  MAX_ORDINARY_LINE_LENGTH,
  classifyLanguage,
  decodeContent,
  detectBinary,
  detectGenerated,
  safeUtf8Cut,
  type BinaryEvidence,
  type BinaryVerdict,
  type ClassificationEvidence,
  type ContentEncoding,
  type DecodedContent,
  type GeneratedEvidence,
  type GeneratedVerdict,
  type LanguageClassification,
  type LanguageId,
} from "./content.js";

export {
  MAX_JSON_SCAN_DEPTH,
  MAX_JSON_SCAN_NODES,
  JSON_SCAN_FAILURE_REASONS,
  scanJsonStructure,
  type JsonScanFailureReason,
  type JsonScanResult,
} from "./json-scan.js";

export {
  DEPENDENCY_KINDS,
  DEPENDENCY_SOURCES,
  MANIFEST_FORMAT_IDS,
  MANIFEST_PARSER_VERSIONS,
  MANIFEST_STATUSES,
  detectManifestFormat,
  extractManifest,
  type DependencyKind,
  type DependencyRecord,
  type DependencySource,
  type ManifestExtraction,
  type ManifestFormatId,
  type ManifestRecord,
  type ManifestStatus,
} from "./manifest-formats.js";

export {
  FIELD_WEIGHTS,
  IDF_SCALE,
  LENGTH_NORMALIZER,
  LEXICAL_ALGORITHM_VERSION,
  LEXICAL_FIELDS,
  MAX_TERM_LENGTH,
  MIN_TERM_LENGTH,
  TF_CAP,
  buildLexicalIndex,
  buildTermVector,
  extractSymbols,
  findExactTerm,
  findPrefixTerms,
  inverseDocumentFrequency,
  matchesPathQuery,
  tokenize,
  type EntryTermVector,
  type FieldTerm,
  type LexicalDocument,
  type LexicalField,
  type LexicalIndex,
  type LexicalLimits,
  type LexicalPosting,
  type LexicalTermEntry,
  type ScoreComponent,
} from "./lexical.js";

export {
  REJECTION_REASONS,
  REPOSITORY_CHANGE_TYPES,
  REPOSITORY_INDEX_CHANGE_SET_SCHEMA_VERSION,
  REPOSITORY_INDEX_SCHEMA_VERSION,
  TOMBSTONE_REASONS,
  compareDiagnostics,
  compareEntries,
  digestOf,
  digestOfBytes,
  parseRepositoryIndex,
  parseRepositoryIndexChangeSet,
  repositoryIndexFingerprint,
  revisionId,
  sealRepositoryIndex,
  type EntryProvenance,
  type RejectionReason,
  type RepositoryChange,
  type RepositoryIndex,
  type RepositoryIndexChangeSet,
  type RepositoryIndexEntry,
  type RepositoryIndexIdentity,
  type RepositoryIndexRejection,
  type RepositoryIndexTombstone,
  type RepositoryIndexTotals,
  type TombstoneReason,
} from "./index-model.js";

export {
  DEFAULT_MAX_CANDIDATES,
  DEFAULT_QUERY_LIMIT,
  MAX_QUERY_LIMIT,
  MAX_QUERY_TERMS,
  QUERY_KINDS,
  buildRepositoryIndex,
  createRepositoryIndexer,
  queryRepositoryIndex,
  tombstoneFingerprint,
  updateRepositoryIndex,
  type BuildRepositoryIndexOptions,
  type QueryKind,
  type RepositoryIndexQuery,
  type RepositoryIndexSearchHit,
  type RepositoryIndexSearchResult,
  type RepositoryIndexer,
  type UpdateRepositoryIndexOptions,
} from "./indexer.js";
