import { inspect } from "node:util";
import { describe, expect, it } from "vitest";
import { defaultDataHandlingPolicy, ValidationError } from "@ai-dev-os/domain";
import { createDeterministicPolicyBroker, createManualPolicyClock, parsePolicyRequest, parsePolicyRule } from "@ai-dev-os/policy";
import {
  SecretBrokerError,
  containsSecretLikeKey,
  createPolicyAwareSecretResolver,
  createSecretMaterial,
  parseSecretAccessContext,
  parseSecretRef,
  redactSecretText,
  secretRefFingerprint,
  secretRefDisplay,
  serializeSecretRef,
  type SecretBroker,
  type SecretMaterial,
} from "../src/index.js";

const refs = [
  { schemaVersion: 1, type: "named", namespace: "provider", name: "primary", version: "v1", expectedKind: "text", providerInstanceId: "provider-1" },
  { schemaVersion: 1, type: "environment", namespace: "launch", variableName: "AI_DEV_OS_KEY", version: null, expectedKind: "text", providerInstanceId: null },
  { schemaVersion: 1, type: "keychain", namespace: "desktop", service: "ai-dev-os", account: "primary", version: null, expectedKind: "text", providerInstanceId: null },
  { schemaVersion: 1, type: "encrypted-file", namespace: "desktop", containerId: "container-1", entryName: "primary", version: "2", expectedKind: "bytes", providerInstanceId: null },
  { schemaVersion: 1, type: "external-vault", namespace: "team", vaultNamespace: "engineering", pathSegments: ["providers", "primary"], entryName: "credential", version: "42", expectedKind: "text", providerInstanceId: "provider-1" },
] as const;
const context = parseSecretAccessContext({ operationId: "operation-1", providerInstanceId: "provider-1", purpose: "provider-authentication", requestedLifetimeMs: 1_000, accessForm: "text", classification: "internal", projectId: "project-1", taskId: "task-1", approvalEvidenceRefs: [], disclosureDecisionFingerprint: null, locality: "local", trace: { traceId: "trace-1", runId: "run-1", taskId: "task-1", taskRunId: "attempt-1" }, deadline: null, signal: undefined });

describe("secret references and material", () => {
  it("parses every finite reference form into immutable canonical output", () => { for (const ref of refs) { const parsed = parseSecretRef(ref); expect(Object.isFrozen(parsed)).toBe(true); expect(JSON.parse(serializeSecretRef(parsed)).type).toBe(ref.type); expect(secretRefDisplay(parsed)).toContain(`[${ref.expectedKind}]`); expect(secretRefFingerprint(parsed)).toHaveLength(64); } });
  it("rejects unknown variants, paths, inline values, hostile prototypes, and binary environment references", () => { expect(() => parseSecretRef({ ...refs[0], type: "inline", value: "secret-canary" })).toThrow(); expect(() => parseSecretRef({ ...refs[4], pathSegments: [".."] })).toThrow(); expect(() => parseSecretRef({ ...refs[0], secretValue: "canary" })).toThrow(); expect(() => parseSecretRef(Object.create({ polluted: true }))).toThrow(ValidationError); expect(() => parseSecretRef({ ...refs[1], expectedKind: "bytes" })).toThrow(); });
  it("keeps material redacted, kind-safe, disposable, and non-enumerable by value", async () => { const material = createSecretMaterial("text", new TextEncoder().encode("material-secret")); expect(await material.useText((value) => value.length)).toBe(15); await expect(material.useBytes((value) => value.length)).rejects.toMatchObject({ code: "KIND_MISMATCH" }); expect(String(material)).toBe("[REDACTED SECRET]"); expect(JSON.stringify(material)).not.toContain("material-secret"); expect(inspect(material)).toBe("[REDACTED SECRET]"); expect(Object.keys(material)).not.toContain("value"); material.dispose(); await expect(material.useText((value) => value)).rejects.toMatchObject({ code: "MATERIAL_DISPOSED" }); material.dispose(); });
  it("scopes binary copies, clears them on failure, and exposes only the declared kind", async () => { const material = createSecretMaterial("bytes", new Uint8Array([4, 5, 6])); expect(material.kind).toBe("bytes"); expect(await material.useBytes((bytes) => [...bytes])).toEqual([4, 5, 6]); await expect(material.useText((value) => value)).rejects.toMatchObject({ code: "KIND_MISMATCH" }); await expect(material.useBytes(() => { throw new Error("consumer"); })).rejects.toThrow("consumer"); material.dispose(); });
  it("detects secret-like configuration keys conservatively and provides fixed redaction markers", () => { expect(containsSecretLikeKey({ nested: [{ apiKey: "x" }] })).toBe(true); expect(containsSecretLikeKey({ credentialRef: refs[0] })).toBe(false); const cyclic: { self?: unknown } = {}; cyclic.self = cyclic; expect(containsSecretLikeKey(cyclic)).toBe(true); expect(redactSecretText("")).toBe("[REDACTED SECRET:EMPTY]"); expect(redactSecretText("x")).toBe("[REDACTED SECRET]"); expect(redactSecretText(null)).toBe("[REDACTED SECRET]"); });
  it("validates access context bounds, evidence uniqueness, fingerprints, deadlines, and signals", () => { expect(() => parseSecretAccessContext({ ...context, requestedLifetimeMs: 0 })).toThrow(); expect(() => parseSecretAccessContext({ ...context, approvalEvidenceRefs: ["a", "a"] })).toThrow(); expect(() => parseSecretAccessContext({ ...context, disclosureDecisionFingerprint: "bad" })).toThrow(); expect(() => parseSecretAccessContext({ ...context, signal: {} })).toThrow(); const signal = { aborted: false, addEventListener: () => undefined }; const full = parseSecretAccessContext({ ...context, disclosureDecisionFingerprint: "a".repeat(64), deadline: "2026-08-02T01:00:00.000Z", signal }); expect(full.deadline).not.toBeNull(); expect(full.signal).toBe(signal); });
  it("serializes broker errors through bounded safe metadata", () => { const error = new SecretBrokerError("NOT_FOUND", "Missing.", { referenceType: "named" }, "fixture"); expect(error.toJSON()).toEqual(expect.objectContaining({ code: "NOT_FOUND", causeCategory: "fixture" })); });
});

describe("policy-before-resolution composition", () => {
  function policy(effect: "allow" | "deny" | "conditional", approval: null | { approverClass: "user"; usage: "one-shot"; ttlMs: number } = null) { const rule = parsePolicyRule({ schemaVersion: 1, id: `secret-${effect}`, authority: "organization", effect, actions: ["secret-access"], classifications: [], risks: [], requiredTransformations: [], approval, requiredLocality: "any", forbidInputLogging: false, forbidOutputLogging: false, forbidArtifactPersistence: false, forbidRetention: false, maxRetentionDays: null, forbiddenCapabilities: [] }); return createDeterministicPolicyBroker({ policyVersion: "v1", rules: [rule], clock: createManualPolicyClock() }); }
  function request(approvalEvidence: readonly unknown[] = []) { return parsePolicyRequest({ schemaVersion: 1, action: "secret-access", classification: "internal", handlingPolicy: defaultDataHandlingPolicy("internal"), risk: "low", locality: "local", provider: null, model: null, scope: { projectId: "project-1", taskId: "task-1", providerInstanceId: "provider-1", workspaceId: null, operationId: "operation-1", traceId: "trace-1" }, subjectDigest: secretRefFingerprint(parseSecretRef(refs[0])), requestedCapabilities: [], transformationsApplied: [], approvalEvidence, retentionDays: null, trace: context.trace, requesterKind: "user" }); }
  function countingBroker(counter: { value: number }): SecretBroker { return { describeCapabilities: () => ({ resolve: true, availability: true, replace: false, revoke: false, versions: false, kinds: ["text"] }), availability: async () => { throw new Error("unused"); }, async withSecret<T>(_ref, _context, callback) { counter.value += 1; const material = createSecretMaterial("text", new TextEncoder().encode("value")); try { return await callback(material); } finally { material.dispose(); } }, replace: async () => { throw new SecretBrokerError("UNSUPPORTED_OPERATION", "Unsupported."); }, revoke: async () => { throw new SecretBrokerError("UNSUPPORTED_OPERATION", "Unsupported."); }, close: async () => undefined }; }

  it("does not invoke the broker when policy denies", async () => { const counter = { value: 0 }; const resolver = createPolicyAwareSecretResolver({ policy: policy("deny"), broker: countingBroker(counter) }); await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); expect(counter.value).toBe(0); });
  it("withholds conditional access until structured approval is valid", async () => { const counter = { value: 0 }; const broker = policy("conditional", { approverClass: "user", usage: "one-shot", ttlMs: 600_000 }); const resolver = createPolicyAwareSecretResolver({ policy: broker, broker: countingBroker(counter) }); const pending = broker.evaluate(request()); await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); expect(counter.value).toBe(0); const requirement = pending.requiredApprovals[0]!; const evidence = { approvalRequestId: requirement.approvalRequestId, action: "secret-access", risk: "low", scope: requirement.scope, subjectDigest: requirement.subjectDigest, usage: "one-shot", approverClass: "user", approverIdentityRef: "identity-1", result: "approved", decidedAt: "2026-08-02T00:00:00.000Z", expiresAt: "2026-08-02T00:10:00.000Z", revokedAt: null, consumedAt: null, evidenceRef: "evidence-1" }; const approvedContext = parseSecretAccessContext({ ...context, approvalEvidenceRefs: ["evidence-1"] }); const result = await resolver.withSecret({ ref: parseSecretRef(refs[0]), context: approvedContext, policyRequest: request([evidence]) }, (secret) => secret.useText((value) => value)); expect(result.value).toBe("value"); expect(result.decisionFingerprint).toHaveLength(64); expect(counter.value).toBe(1); });
  it("rejects mismatched policy scope and non-secret policy actions before the broker", async () => { const counter = { value: 0 }; const resolver = createPolicyAwareSecretResolver({ policy: policy("allow"), broker: countingBroker(counter) }); await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context: { ...context, operationId: "other" }, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); const wrong = parsePolicyRequest({ ...request(), action: "workspace-read" }); await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: wrong }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); expect(counter.value).toBe(0); });
  it("binds the complete trace and supplies the allowed decision fingerprint before secret use", async () => { const counter = { value: 0 }; const resolver = createPolicyAwareSecretResolver({ policy: policy("allow"), broker: countingBroker(counter) }); for (const trace of [{ ...context.trace, runId: "other-run" }, { ...context.trace, taskId: "other-task" }, { ...context.trace, taskRunId: "other-attempt" }]) { await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context: { ...context, trace }, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); } expect(counter.value).toBe(0); let callbackFingerprint = ""; const result = await resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, (_secret, fingerprint) => { callbackFingerprint = fingerprint; return 1; }); expect(callbackFingerprint).toMatch(/^[a-f0-9]{64}$/); expect(result.decisionFingerprint).toBe(callbackFingerprint); expect(counter.value).toBe(1); });
  it("captures exact policy and broker methods against option, method, or bind substitution", async () => { const counter = { value: 0 }; const denied = policy("deny"); const broker = countingBroker(counter); const options = { policy: denied, broker }; const resolver = createPolicyAwareSecretResolver(options); options.policy = policy("allow"); broker.withSecret = async (_ref, _context, callback) => { counter.value += 100; const material = createSecretMaterial("text", new TextEncoder().encode("value")); try { return await callback(material); } finally { material.dispose(); } }; await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); expect(counter.value).toBe(0); const evaluate = denied.evaluate; Object.defineProperty(evaluate, "bind", { value: () => () => ({ outcome: "allowed", code: "POLICY_ALLOWED", fingerprint: "f".repeat(64) }) }); const shadowedBind = createPolicyAwareSecretResolver({ policy: { evaluate }, broker: countingBroker(counter) }); await expect(shadowedBind.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); expect(counter.value).toBe(0); for (const invalid of [new Proxy({ policy: denied, broker }, {}), { policy: denied, broker, extra: true }, Object.defineProperty({ broker }, "policy", { enumerable: true, get: () => denied })]) expect(() => createPolicyAwareSecretResolver(invalid as never)).toThrow(SecretBrokerError); });
  it("rejects malformed or throwing allowed policy decisions before broker access", async () => { const counter = { value: 0 }; const broker = countingBroker(counter); for (const decision of [{ outcome: "allowed", code: "POLICY_ALLOWED", fingerprint: "invalid" }, Object.defineProperty({ outcome: "allowed", code: "POLICY_ALLOWED" }, "fingerprint", { enumerable: true, get: () => { throw new Error("private-policy-canary"); } })]) { const resolver = createPolicyAwareSecretResolver({ policy: { evaluate: () => decision as never }, broker }); await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED", message: "The secret access policy decision is invalid." }); } for (const thrown of [new Error("private-policy-canary"), new SecretBrokerError("BACKEND_FAILURE", "private-policy-canary", { detail: "private-policy-canary" }, "private-policy-canary")]) { const throwing = createPolicyAwareSecretResolver({ policy: { evaluate: () => { throw thrown; } }, broker }); const error = await throwing.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, () => undefined).catch((value: unknown) => value); expect(error).toMatchObject({ code: "ACCESS_DENIED", message: "The secret access policy evaluation failed.", details: {}, causeCategory: null }); expect(JSON.stringify(error)).not.toContain("private-policy-canary"); } expect(counter.value).toBe(0); });
  it("rejects an invalid consumer callback before policy evaluation or broker access", async () => { const evaluated = { value: 0 }; const counter = { value: 0 }; const allowed = policy("allow"); const resolver = createPolicyAwareSecretResolver({ policy: { evaluate(value) { evaluated.value += 1; return allowed.evaluate(value); } }, broker: countingBroker(counter) }); await expect(resolver.withSecret({ ref: parseSecretRef(refs[0]), context, policyRequest: request() }, 1 as never)).rejects.toMatchObject({ code: "INVALID_REFERENCE" }); expect(evaluated.value).toBe(0); expect(counter.value).toBe(0); });
  it("rejects hostile resolver input projections before policy evaluation or broker access", async () => { const evaluated = { value: 0 }; const counter = { value: 0 }; const allowed = policy("allow"); const resolver = createPolicyAwareSecretResolver({ policy: { evaluate(value) { evaluated.value += 1; return allowed.evaluate(value); } }, broker: countingBroker(counter) }); const base = { ref: parseSecretRef(refs[0]), context, policyRequest: request() }; for (const input of [new Proxy(base, {}), { ...base, extra: true }, { ...base, [Symbol("hidden")]: true }, Object.defineProperty({ context, policyRequest: request() }, "ref", { enumerable: true, get: () => { throw new Error("private-input-canary"); } }), { ...base, ref: new Proxy(base.ref, {}) }]) { const error = await resolver.withSecret(input as never, () => undefined).catch((value: unknown) => value); expect(error).toMatchObject({ code: "INVALID_REFERENCE", message: "The secret resolver input is invalid." }); expect(JSON.stringify(error)).not.toContain("private-input-canary"); } expect(evaluated.value).toBe(0); expect(counter.value).toBe(0); });
});
