/**
 * Managed private repositories and worktrees.
 *
 * A writing attempt never operates in the user's working tree, and its
 * worktree is never attached to the user's repository either. `git worktree
 * add` writes administrative state into the repository it is run against —
 * a `worktrees/<name>` directory inside `.git` — so pointing it at the source
 * repository would mutate exactly what this stage promises not to touch.
 *
 * Instead a private bare repository is created under the managed root. It
 * borrows the source objects read-only through `objects/info/alternates` and
 * owns the snapshot objects, so it can check out the snapshot on its own. All
 * worktree bookkeeping then lands in the managed repository.
 *
 * Cleanup never deletes a computed path on trust. A directory is removed only
 * after its resolved identity is confirmed to be inside the managed root and
 * an ownership marker written at creation is found and matches.
 */

import { mkdir, readFile, realpath, rm, writeFile } from "node:fs/promises";
import { isAbsolute, join, resolve, sep } from "node:path";
import { randomBytes } from "node:crypto";
import { WorkspaceError, causeCategory, invalidConfiguration } from "./errors.js";
import { runGitChecked } from "./git-runner.js";
import type { GitRuntime } from "./runtime.js";
import type { RepositorySnapshot } from "./snapshot.js";

export const OWNERSHIP_MARKER_FILE = ".ai-dev-os-workspace.json";
export const OWNERSHIP_MARKER_VERSION = 1 as const;

export const WORKSPACE_STATES = Object.freeze([
  "creating",
  "ready",
  "leased",
  "active",
  "sealing",
  "completed",
  "failed",
  "expired",
  "cleaning",
  "cleaned",
  "orphaned",
] as const);
export type WorkspaceState = (typeof WORKSPACE_STATES)[number];

export interface OwnershipMarker {
  readonly schemaVersion: typeof OWNERSHIP_MARKER_VERSION;
  readonly workspaceId: string;
  readonly projectId: string;
  readonly attemptId: string;
  readonly snapshotId: string;
  readonly createdAt: string;
  readonly nonce: string;
}

export interface ManagedWorkspaceRecord {
  readonly workspaceId: string;
  readonly projectId: string;
  readonly attemptId: string;
  readonly snapshotId: string;
  readonly baseCommit: string;
  readonly snapshotCommit: string;
  /** Generated by this package; never supplied by a caller. */
  readonly managedRoot: string;
  readonly repositoryDir: string;
  readonly worktreeDir: string;
  readonly branchRef: string;
  readonly state: WorkspaceState;
  readonly createdAt: string;
  readonly expiresAt: string;
  readonly policyFingerprint: string;
  readonly version: number;
}

export interface CreateWorkspaceOptions {
  readonly projectId: string;
  readonly workspaceId: string;
  readonly attemptId: string;
  readonly snapshot: RepositorySnapshot;
  /** Absolute directory this package owns and may create inside. */
  readonly managedRootBase: string;
  readonly createdAt: string;
  readonly expiresAt: string;
  readonly policyFingerprint: string;
  readonly nonceSource?: () => string;
  readonly timeoutMs?: number;
}

const IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw invalidConfiguration("An identifier is not safe for use in a generated path.", {
      field: label,
    });
  }
}

/**
 * Creates the managed private repository and its worktree.
 *
 * On any failure the partially created directory is removed through the same
 * ownership-checked path used for ordinary cleanup, so a half-built workspace
 * never accumulates and never becomes something a later sweep deletes blindly.
 */
export async function createManagedWorkspace(
  runtime: GitRuntime,
  options: CreateWorkspaceOptions,
): Promise<ManagedWorkspaceRecord> {
  assertIdentifier(options.projectId, "projectId");
  assertIdentifier(options.workspaceId, "workspaceId");
  assertIdentifier(options.attemptId, "attemptId");
  if (!isAbsolute(options.managedRootBase)) {
    throw invalidConfiguration("The managed root must be an absolute path.");
  }

  const nonce = (options.nonceSource ?? (() => randomBytes(8).toString("hex")))();
  if (!/^[a-f0-9]{16}$/.test(nonce)) {
    throw invalidConfiguration("The workspace nonce source must return 16 lowercase hex characters.");
  }

  // The path is generated from validated identifiers plus entropy. A caller
  // cannot choose it, so a caller cannot aim it at something already there.
  const managedRoot = join(
    resolve(options.managedRootBase),
    `${options.projectId}-${options.attemptId}-${nonce}`,
  );
  const repositoryDir = join(managedRoot, "repo.git");
  const worktreeDir = join(managedRoot, "worktree");
  const branchRef = `refs/ai-dev-os/attempt-${options.attemptId}-${nonce}`;

  try {
    // Exclusive creation: an existing directory is a collision, not a reuse.
    await mkdir(managedRoot, { recursive: false });
  } catch (error) {
    throw new WorkspaceError("GIT_BACKEND_FAILURE", "The managed workspace root could not be created.", {
      cause: causeCategory(error),
    });
  }

  try {
    const marker: OwnershipMarker = Object.freeze({
      schemaVersion: OWNERSHIP_MARKER_VERSION,
      workspaceId: options.workspaceId,
      projectId: options.projectId,
      attemptId: options.attemptId,
      snapshotId: options.snapshot.snapshotId,
      createdAt: options.createdAt,
      nonce,
    });
    await writeFile(join(managedRoot, OWNERSHIP_MARKER_FILE), JSON.stringify(marker), {
      flag: "wx",
    });

    const config = runtime.configArguments();
    const env = runtime.environment();
    const base = {
      cwd: managedRoot,
      env,
      ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }),
    };

    await runGitChecked(
      runtime.runner,
      [
        ...config,
        "init",
        "--bare",
        "--quiet",
        `--object-format=${options.snapshot.objectFormat}`,
        "--",
        repositoryDir,
      ],
      { ...base, operation: "init-managed-repo" },
    );

    // Borrow the snapshot's objects read-only. The file must be LF-terminated
    // and contain one absolute directory per line.
    const alternates = [
      options.snapshot.privateObjectDir,
      ...options.snapshot.borrowedObjectDirs,
    ]
      .map((directory) => directory.replace(/\\/g, "/"))
      .join("\n");
    await mkdir(join(repositoryDir, "objects", "info"), { recursive: true });
    await writeFile(join(repositoryDir, "objects", "info", "alternates"), `${alternates}\n`, {
      flag: "w",
    });

    // Point a generated ref at the snapshot so the checkout names a ref we
    // control rather than any branch the user has.
    await runGitChecked(
      runtime.runner,
      [...config, "update-ref", branchRef, options.snapshot.snapshotCommit],
      { ...base, cwd: repositoryDir, operation: "update-ref" },
    );

    // Detached: no user branch is ever checked out in a managed worktree.
    await runGitChecked(
      runtime.runner,
      [
        ...config,
        "-C",
        repositoryDir,
        "worktree",
        "add",
        "--detach",
        "--quiet",
        "--",
        worktreeDir,
        options.snapshot.snapshotCommit,
      ],
      { ...base, operation: "worktree-add" },
    );

    return Object.freeze({
      workspaceId: options.workspaceId,
      projectId: options.projectId,
      attemptId: options.attemptId,
      snapshotId: options.snapshot.snapshotId,
      baseCommit: options.snapshot.baseCommit,
      snapshotCommit: options.snapshot.snapshotCommit,
      managedRoot,
      repositoryDir,
      worktreeDir,
      branchRef,
      state: "ready",
      createdAt: options.createdAt,
      expiresAt: options.expiresAt,
      policyFingerprint: options.policyFingerprint,
      version: 1,
    });
  } catch (error) {
    // Reconcile the partial creation through the ownership-checked path.
    await removeManagedDirectory(managedRoot, resolve(options.managedRootBase)).catch(
      () => undefined,
    );
    throw error instanceof WorkspaceError
      ? error
      : new WorkspaceError("GIT_BACKEND_FAILURE", "The managed workspace could not be created.", {
          cause: causeCategory(error),
        });
  }
}

export interface CleanupOptions {
  readonly record: ManagedWorkspaceRecord;
  readonly managedRootBase: string;
  /** Cleanup is refused while a lease is live. */
  readonly leaseActive: boolean;
  readonly force?: boolean;
}

export interface CleanupResult {
  readonly workspaceId: string;
  readonly removed: boolean;
  readonly alreadyClean: boolean;
}

/**
 * Removes one managed workspace.
 *
 * Idempotent: removing an already-removed workspace succeeds and reports
 * `alreadyClean`. Refused while a lease is active, because the process
 * holding it may still be writing.
 */
export async function cleanupManagedWorkspace(options: CleanupOptions): Promise<CleanupResult> {
  const { record } = options;
  if (options.leaseActive && options.force !== true) {
    throw new WorkspaceError(
      "CLEANUP_REFUSED",
      "A workspace with an active lease cannot be cleaned up.",
      { workspaceId: record.workspaceId },
    );
  }

  const marker = await readOwnershipMarker(record.managedRoot);
  if (marker === null) {
    // Nothing of ours is there. Removing an unmarked directory would risk
    // deleting something this package never created.
    return Object.freeze({
      workspaceId: record.workspaceId,
      removed: false,
      alreadyClean: true,
    });
  }
  if (
    marker.workspaceId !== record.workspaceId ||
    marker.projectId !== record.projectId ||
    marker.attemptId !== record.attemptId
  ) {
    throw new WorkspaceError(
      "CLEANUP_OWNERSHIP_MISMATCH",
      "The ownership marker does not match the workspace being cleaned up.",
      { workspaceId: record.workspaceId },
    );
  }

  await removeManagedDirectory(record.managedRoot, resolve(options.managedRootBase));
  return Object.freeze({ workspaceId: record.workspaceId, removed: true, alreadyClean: false });
}

export async function readOwnershipMarker(managedRoot: string): Promise<OwnershipMarker | null> {
  try {
    const raw = await readFile(join(managedRoot, OWNERSHIP_MARKER_FILE), "utf8");
    if (raw.length > 4_096) {
      return null;
    }
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null) {
      return null;
    }
    const record = parsed as Record<string, unknown>;
    if (record["schemaVersion"] !== OWNERSHIP_MARKER_VERSION) {
      return null;
    }
    const read = (key: string): string =>
      typeof record[key] === "string" ? (record[key] as string) : "";
    return Object.freeze({
      schemaVersion: OWNERSHIP_MARKER_VERSION,
      workspaceId: read("workspaceId"),
      projectId: read("projectId"),
      attemptId: read("attemptId"),
      snapshotId: read("snapshotId"),
      createdAt: read("createdAt"),
      nonce: read("nonce"),
    });
  } catch {
    return null;
  }
}

/**
 * Deletes a directory only after proving where it actually is.
 *
 * The path is resolved through every link before the containment test, so a
 * symbolic link or a junction planted inside the managed root cannot redirect
 * the deletion somewhere else. `fs.rm` does not traverse into a link's target,
 * but the root itself being a link is the case that matters here.
 */
export async function removeManagedDirectory(
  target: string,
  managedRootBase: string,
): Promise<void> {
  let resolvedTarget: string;
  let resolvedBase: string;
  try {
    resolvedTarget = await realpath(target);
  } catch (error) {
    if (causeCategory(error) === "ENOENT") {
      return;
    }
    throw new WorkspaceError("CLEANUP_REFUSED", "The cleanup target could not be resolved.", {
      cause: causeCategory(error),
    });
  }
  try {
    resolvedBase = await realpath(managedRootBase);
  } catch (error) {
    throw new WorkspaceError("CLEANUP_REFUSED", "The managed root could not be resolved.", {
      cause: causeCategory(error),
    });
  }

  const prefix = resolvedBase.endsWith(sep) ? resolvedBase : `${resolvedBase}${sep}`;
  if (resolvedTarget === resolvedBase || !resolvedTarget.startsWith(prefix)) {
    throw new WorkspaceError(
      "CLEANUP_OWNERSHIP_MISMATCH",
      "The cleanup target resolves outside the managed root.",
      {},
    );
  }

  await rm(resolvedTarget, { recursive: true, force: true });
}

/**
 * Finds managed workspaces that outlived their expiry.
 *
 * Discovery is bounded to direct children of the managed root and only
 * reports directories carrying a valid ownership marker, so a foreign
 * directory sharing the location is listed by nobody and deleted by nobody.
 */
export async function findStaleWorkspaces(input: {
  readonly managedRootBase: string;
  readonly now: Date;
  readonly olderThanMs: number;
  readonly maxResults?: number;
}): Promise<readonly OwnershipMarker[]> {
  const { readdir } = await import("node:fs/promises");
  const limit = input.maxResults ?? 1_000;
  let entries;
  try {
    entries = await readdir(input.managedRootBase, { withFileTypes: true });
  } catch {
    return Object.freeze([]);
  }
  const cutoff = input.now.valueOf() - input.olderThanMs;
  const stale: OwnershipMarker[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || stale.length >= limit) {
      continue;
    }
    const marker = await readOwnershipMarker(join(input.managedRootBase, entry.name));
    if (marker === null) {
      continue;
    }
    const createdAt = new Date(marker.createdAt).valueOf();
    if (Number.isFinite(createdAt) && createdAt <= cutoff) {
      stale.push(marker);
    }
  }
  return Object.freeze(stale);
}

export function transitionWorkspace(
  record: ManagedWorkspaceRecord,
  next: WorkspaceState,
): ManagedWorkspaceRecord {
  const allowed = LEGAL_TRANSITIONS[record.state];
  if (!allowed.includes(next)) {
    throw new WorkspaceError("WORKSPACE_NOT_READY", "The workspace state transition is not legal.", {
      from: record.state,
      to: next,
    });
  }
  return Object.freeze({ ...record, state: next, version: record.version + 1 });
}

const LEGAL_TRANSITIONS: Readonly<Record<WorkspaceState, readonly WorkspaceState[]>> = Object.freeze({
  creating: ["ready", "failed", "cleaning"],
  ready: ["leased", "expired", "cleaning", "failed"],
  leased: ["active", "expired", "failed", "cleaning"],
  active: ["sealing", "failed", "expired", "cleaning"],
  sealing: ["completed", "failed", "cleaning"],
  completed: ["cleaning"],
  failed: ["cleaning"],
  expired: ["cleaning", "orphaned"],
  cleaning: ["cleaned", "orphaned"],
  cleaned: [],
  orphaned: ["cleaning"],
});
