import { inspect } from "node:util";
import { describe, expect, it } from "vitest";
import { SecretBrokerError, type SecretAccessContext, type SecretAuditRecord, type SecretBroker, type SecretRef } from "../secrets.js";

export interface SecretBrokerContractHarness {
  readonly broker: SecretBroker;
  readonly textRef: SecretRef;
  readonly emptyTextRef: SecretRef;
  readonly bytesRef: SecretRef;
  readonly deniedRef: SecretRef;
  readonly missingRef: SecretRef;
  readonly context: SecretAccessContext;
  readonly audits: readonly SecretAuditRecord[];
  readonly zeroRecords: readonly { readonly reason: string; readonly byteLength: number; readonly allZero: boolean }[];
  readonly sourceBytes: Uint8Array;
}
export type SecretBrokerContractFactory = () => SecretBrokerContractHarness;

export function runSecretBrokerContractSuite(factory: SecretBrokerContractFactory): void {
  describe("secret broker contract", () => {
    it("resolves text and byte secrets only through scoped access", async () => { const h = factory(); const text = await h.broker.withSecret(h.textRef, h.context, (secret) => secret.useText((value) => value)); expect(text).toBe("test-secret-value"); const bytes = await h.broker.withSecret(h.bytesRef, { ...h.context, accessForm: "bytes" }, (secret) => secret.useBytes((value) => [...value])); expect(bytes).toEqual([1, 2, 3, 4]); await h.broker.close(); });
    it("distinguishes empty text from missing", async () => { const h = factory(); expect(await h.broker.withSecret(h.emptyTextRef, h.context, (secret) => secret.useText((value) => value))).toBe(""); await expect(h.broker.withSecret(h.missingRef, h.context, () => undefined)).rejects.toMatchObject({ code: "NOT_FOUND" }); await h.broker.close(); });
    it("reports availability without revealing values", async () => { const h = factory(); expect((await h.broker.availability(h.textRef, h.context)).available).toBe(true); const missing = await h.broker.availability(h.missingRef, h.context); expect(missing).toMatchObject({ available: false, reason: "not-found" }); expect(JSON.stringify(missing)).not.toContain("test-secret-value"); await h.broker.close(); });
    it("rejects wrong versions, access denial, wrong kinds, and context mismatches", async () => { const h = factory(); await expect(h.broker.withSecret({ ...h.textRef, version: "other" } as SecretRef, h.context, () => undefined)).rejects.toMatchObject({ code: "VERSION_UNAVAILABLE" }); await expect(h.broker.withSecret(h.deniedRef, h.context, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); await expect(h.broker.withSecret({ ...h.textRef, expectedKind: "bytes" } as SecretRef, { ...h.context, accessForm: "bytes" }, () => undefined)).rejects.toMatchObject({ code: "KIND_MISMATCH" }); await expect(h.broker.withSecret(h.textRef, { ...h.context, providerInstanceId: "wrong" }, () => undefined)).rejects.toMatchObject({ code: "ACCESS_DENIED" }); await h.broker.close(); });
    it("wraps callback failures without callback data", async () => { const h = factory(); const canary = "callback-secret-canary"; await expect(h.broker.withSecret(h.textRef, h.context, async () => { throw new Error(canary); })).rejects.toMatchObject({ code: "CONSUMER_FAILURE", causeCategory: "Error" }); try { await h.broker.withSecret(h.textRef, h.context, () => { throw new Error(canary); }); } catch (error) { expect(JSON.stringify(error)).not.toContain(canary); } await h.broker.close(); });
    it("disposes material after callbacks and prevents common inspection leakage", async () => { const h = factory(); let captured: import("../secrets.js").SecretMaterial | undefined; await h.broker.withSecret(h.textRef, h.context, async (secret) => { captured = secret; expect(String(secret)).toBe("[REDACTED SECRET]"); expect(JSON.stringify(secret)).toBe('"[REDACTED SECRET]"'); expect(inspect(secret)).toBe("[REDACTED SECRET]"); expect(Object.keys(secret)).not.toContain("value"); }); await expect(captured!.useText((value) => value)).rejects.toMatchObject({ code: "MATERIAL_DISPOSED" }); await h.broker.close(); });
    it("defensively copies seed bytes and bytes exposed to consumers", async () => { const h = factory(); h.sourceBytes.fill(9); await h.broker.withSecret(h.bytesRef, { ...h.context, accessForm: "bytes" }, async (secret) => { await secret.useBytes((bytes) => { expect([...bytes]).toEqual([1, 2, 3, 4]); bytes.fill(7); }); }); const after = await h.broker.withSecret(h.bytesRef, { ...h.context, accessForm: "bytes" }, (secret) => secret.useBytes((bytes) => [...bytes])); expect(after).toEqual([1, 2, 3, 4]); await h.broker.close(); });
    it("replaces and revokes while emitting safe deterministic attempt/outcome audits", async () => { const h = factory(); await h.broker.replace(h.textRef, { kind: "text", text: "replacement" }, h.context); expect(await h.broker.withSecret(h.textRef, h.context, (secret) => secret.useText((value) => value))).toBe("replacement"); await h.broker.revoke(h.textRef, h.context); await expect(h.broker.withSecret(h.textRef, h.context, () => undefined)).rejects.toMatchObject({ code: "REVOKED" }); expect(h.zeroRecords.some((item) => item.reason === "replace" && item.allZero)).toBe(true); expect(h.zeroRecords.some((item) => item.reason === "revoke" && item.allZero)).toBe(true); expect(h.audits.some((item) => item.operation === "resolve" && item.phase === "attempt" && item.outcome === null)).toBe(true); expect(h.audits.some((item) => item.operation === "resolve" && item.phase === "outcome" && item.outcome === "success")).toBe(true); expect(JSON.stringify(h.audits)).not.toContain("replacement"); await h.broker.close(); });
    it("uses snapshot semantics for concurrent resolution and replacement", async () => { const h = factory(); let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const active = h.broker.withSecret(h.textRef, h.context, async (secret) => secret.useText(async (value) => { await gate; return value; })); await Promise.resolve(); await h.broker.replace(h.textRef, { kind: "text", text: "new-value" }, h.context); release(); expect(await active).toBe("test-secret-value"); expect(await h.broker.withSecret(h.textRef, h.context, (secret) => secret.useText((value) => value))).toBe("new-value"); await h.broker.close(); });
    it("closes idempotently, zeros owned buffers, and rejects later operations", async () => { const h = factory(); await h.broker.close(); await h.broker.close(); expect(h.zeroRecords.every((item) => item.allZero)).toBe(true); await expect(h.broker.availability(h.textRef, h.context)).rejects.toMatchObject({ code: "BROKER_CLOSED" }); await expect(h.broker.withSecret(h.textRef, h.context, () => undefined)).rejects.toMatchObject({ code: "BROKER_CLOSED" }); await expect(h.broker.replace(h.textRef, { kind: "text", text: "x" }, h.context)).rejects.toMatchObject({ code: "BROKER_CLOSED" }); await expect(h.broker.revoke(h.textRef, h.context)).rejects.toMatchObject({ code: "BROKER_CLOSED" }); });
    it("has a stable capability description and no dump-all API", async () => { const h = factory(); expect(h.broker.describeCapabilities()).toEqual({ resolve: true, availability: true, replace: true, revoke: true, versions: true, kinds: ["bytes", "text"] }); expect("dump" in h.broker).toBe(false); expect("list" in h.broker).toBe(false); await h.broker.close(); });
    it("rejects expired deadlines and pre-aborted access", async () => { const h = factory(); await expect(h.broker.withSecret(h.textRef, { ...h.context, deadline: "2026-08-01T00:00:00.000Z" }, () => undefined)).rejects.toMatchObject({ code: "RESOLUTION_TIMEOUT" }); const signal = { aborted: true, addEventListener: () => undefined }; await expect(h.broker.withSecret(h.textRef, { ...h.context, signal }, () => undefined)).rejects.toMatchObject({ code: "RESOLUTION_TIMEOUT" }); await h.broker.close(); });
    it("never serializes secret values through errors or audit metadata", async () => { const h = factory(); try { await h.broker.withSecret(h.deniedRef, h.context, () => undefined); } catch (error) { expect(error).toBeInstanceOf(SecretBrokerError); expect(JSON.stringify(error)).not.toContain("test-secret-value"); } expect(JSON.stringify(h.audits)).not.toContain("test-secret-value"); await h.broker.close(); });
  });
}
