export {
  MEMORY_ERROR_CODES,
  MemoryError,
  causeCategory,
  failed,
  memoryFailure,
  ok,
  type FailureDetailValue,
  type FailureDetails,
  type MemoryErrorCode,
  type MemoryFailure,
  type MemoryResult,
} from "./errors.js";

export {
  AUTHORIZATION_OUTCOMES,
  MAX_SUBJECT_LENGTH,
  MEMORY_OPERATIONS,
  MEMORY_PURPOSES,
  createMemorySubject,
  createScopedAuthorizer,
  denyAllAuthorizer,
  memoryScopeEquals,
  memoryScopeKey,
  normalizeSubject,
  parseAuthorizationDecision,
  parseMemoryScope,
  parseMemorySubject,
  requireAuthorization,
  type AuthorizationOutcome,
  type MemoryAuthorizationDecision,
  type MemoryAuthorizationRequest,
  type MemoryAuthorizer,
  type MemoryOperation,
  type MemoryPurpose,
  type MemoryScope,
  type MemorySubject,
} from "./scope.js";

export {
  HIGH_ENTROPY_THRESHOLD_BITS,
  REDACTED,
  SECRET_SIGNATURES,
  containsSecretLikeKey,
  detectSecretLikeText,
  opaqueLabel,
  redact,
  sanitizeBodyText,
  shannonEntropyBits,
  type SecretSignature,
  type SecretVerdict,
} from "./redaction.js";

export {
  CONFIDENCE_SCALE,
  DISCLOSURE_SCOPES,
  MAX_BODY_TEXT_LENGTH,
  MAX_LABELS,
  MAX_SOURCES,
  MEMORY_AUTHOR_CLASSES,
  MEMORY_BODY_KINDS,
  MEMORY_CAPTURE_METHODS,
  MEMORY_RECORD_SCHEMA_VERSION,
  MEMORY_RECORD_VARIANTS,
  MEMORY_SOURCE_KINDS,
  WITHHELD_REASONS,
  createMemoryRecord,
  isExpiredAt,
  isExplicitPreference,
  isInferredCandidate,
  memoryContentDigest,
  memoryRecordFingerprint,
  parseMemoryBody,
  parseMemoryRecord,
  type CreateMemoryRecordInput,
  type DisclosureScope,
  type MemoryArtifactReference,
  type MemoryAuthorClass,
  type MemoryBody,
  type MemoryCaptureMethod,
  type MemoryProvenance,
  type MemoryProvenanceSource,
  type MemoryRecord,
  type MemoryRecordVariant,
  type MemorySourceKind,
  type SecretReferenceHandle,
  type WithheldReason,
} from "./record.js";

export {
  APPLY_OUTCOMES,
  CONFIRMATION_STATES,
  MEMORY_EVENT_KINDS,
  parseMemoryEntry,
  type ApplyOutcome,
  type CancellationSignal,
  type ConfirmationState,
  type MemoryApplyCommand,
  type MemoryAuditObserver,
  type MemoryClock,
  type MemoryEntry,
  type MemoryEvent,
  type MemoryEventKind,
  type MemoryIdSource,
  type MemoryStorePort,
} from "./port.js";

export {
  createInMemoryMemoryStore,
  storeFailure,
  withInjectedFailure,
  type InMemoryMemoryStore,
} from "./in-memory-port.js";

export {
  DEFAULT_MEMORY_CONFIGURATION,
  DEFAULT_MEMORY_LIMITS,
  MEMORY_CONFIG_SCHEMA_VERSION,
  memoryConfigurationFingerprint,
  parseMemoryConfiguration,
  withMemoryOverrides,
  type MemoryConfiguration,
  type MemoryLimits,
} from "./config.js";

export {
  appendMemoryRecord,
  confirmMemoryCandidate,
  createMemoryStore,
  memorySnapshot,
  queryMemory,
  rejectMemoryCandidate,
  supersedeMemoryRecord,
  tombstoneMemoryRecord,
  type AppendMemoryInput,
  type CreateMemoryStoreOptions,
  type MemoryQuery,
  type MemoryQueryResult,
  type MemorySnapshot,
  type MemorySnapshotEntry,
  type MemoryStore,
} from "./store.js";
