export {
  CREDENTIAL_UI_SCHEMA_VERSION,
  CREDENTIAL_SLOT_IDS,
  CREDENTIAL_ERROR_CODES,
  type CredentialSlotId,
  type CredentialErrorCode,
  type CredentialVaultState,
  type CredentialRecordState,
  type CredentialOwnership,
  type CredentialValidationOutcome,
  type CredentialRecoveryAction,
  type CredentialDeveloperFacts,
  type CredentialValidationView,
  type CredentialSlotView,
  type CredentialActivitySentence,
  type CredentialRecoveryView,
  type CredentialSlotsResult,
  type ClipboardResult,
  type CredentialMutationResult,
  type CredentialValidatedResult,
  type CredentialCancelledResult,
  type CredentialRefusedResult,
  type CredentialUnknownResult,
  type CredentialResponse,
  type CredentialUiBridge,
} from "./contracts.js";
export { credentialErrorCopy, hasCompleteCredentialErrorCopy, type CredentialErrorCopy } from "./errors.js";
export {
  validationIsDefinitive,
  projectCredentialStatus,
  projectCredentialActions,
  projectCredentialMode,
  actionSetForSlot,
  captureModeActionSet,
  aggregateSummary,
  type PresentationMode,
  type CredentialAction,
  type CredentialActionProjection,
  type CredentialModeSlotProjection,
  type CredentialStatusProjection,
} from "./projections.js";
