import {
  PersistenceError,
  migrationChecksum,
  parseAppliedMigration,
  planMigrations,
  type AppliedMigration,
  type Clock,
  type MigrationDefinition,
  type MigrationStatus,
} from "@ai-dev-os/persistence";
import type { DatabaseClient, DatabasePool } from "./driver.js";

/** Released entries are immutable. Append a new migration instead of editing one. */
export const POSTGRES_MIGRATIONS: readonly MigrationDefinition[] = Object.freeze([
  Object.freeze({
    id: "0001-initial-schema",
    content: `
CREATE TABLE aggregates (
  aggregate_type TEXT COLLATE "C" NOT NULL CHECK (aggregate_type IN ('artifact-manifest','budget-account','project','product-plan','task-graph','task-run','telemetry-ledger','worker-run')),
  aggregate_id TEXT COLLATE "C" NOT NULL,
  schema_version BIGINT NOT NULL CHECK (schema_version BETWEEN 1 AND 1000000),
  aggregate_version BIGINT NOT NULL CHECK (aggregate_version BETWEEN 1 AND 9007199254740991),
  payload TEXT NOT NULL,
  checksum_algorithm TEXT NOT NULL CHECK (checksum_algorithm = 'sha-256'),
  checksum_hex TEXT NOT NULL CHECK (checksum_hex ~ '^[0-9a-f]{64}$'),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  trace_id TEXT,
  PRIMARY KEY (aggregate_type, aggregate_id)
);

CREATE TABLE events (
  event_id TEXT COLLATE "C" PRIMARY KEY,
  aggregate_type TEXT COLLATE "C" NOT NULL CHECK (aggregate_type IN ('artifact-manifest','budget-account','project','product-plan','task-graph','task-run','telemetry-ledger','worker-run')),
  aggregate_id TEXT COLLATE "C" NOT NULL,
  aggregate_version BIGINT NOT NULL CHECK (aggregate_version BETWEEN 1 AND 9007199254740991),
  event_type TEXT NOT NULL,
  event_schema_version BIGINT NOT NULL CHECK (event_schema_version BETWEEN 1 AND 1000000),
  payload TEXT NOT NULL,
  checksum_algorithm TEXT NOT NULL CHECK (checksum_algorithm = 'sha-256'),
  checksum_hex TEXT NOT NULL CHECK (checksum_hex ~ '^[0-9a-f]{64}$'),
  occurred_at TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  global_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 CACHE 1 NO CYCLE) UNIQUE,
  trace_id TEXT,
  causation_id TEXT
);

CREATE INDEX idx_events_aggregate ON events (aggregate_type, aggregate_id, global_sequence);

CREATE TABLE outbox (
  message_id TEXT COLLATE "C" PRIMARY KEY,
  topic TEXT NOT NULL,
  schema_version BIGINT NOT NULL CHECK (schema_version BETWEEN 1 AND 1000000),
  payload TEXT NOT NULL,
  checksum_algorithm TEXT NOT NULL CHECK (checksum_algorithm = 'sha-256'),
  checksum_hex TEXT NOT NULL CHECK (checksum_hex ~ '^[0-9a-f]{64}$'),
  idempotency_key TEXT COLLATE "C" NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('pending','leased','acknowledged','dead-lettered')),
  attempt_count BIGINT NOT NULL CHECK (attempt_count BETWEEN 0 AND 9007199254740991),
  created_at TEXT NOT NULL,
  available_at TEXT NOT NULL,
  lease_owner TEXT,
  lease_expires_at TEXT,
  acknowledged_at TEXT,
  dead_lettered_at TEXT,
  last_failure_category TEXT,
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9007199254740991 CACHE 1 NO CYCLE) UNIQUE,
  trace_id TEXT
);

CREATE INDEX idx_outbox_pending_claim ON outbox (available_at, sequence) WHERE status = 'pending';
CREATE INDEX idx_outbox_leased_claim ON outbox (lease_expires_at, sequence) WHERE status = 'leased';

CREATE TABLE artifacts (
  artifact_id TEXT COLLATE "C" PRIMARY KEY,
  payload TEXT NOT NULL,
  checksum_algorithm TEXT NOT NULL CHECK (checksum_algorithm = 'sha-256'),
  checksum_hex TEXT NOT NULL CHECK (checksum_hex ~ '^[0-9a-f]{64}$')
);

CREATE TABLE artifact_manifests (
  manifest_id TEXT COLLATE "C" PRIMARY KEY,
  payload TEXT NOT NULL,
  checksum_algorithm TEXT NOT NULL CHECK (checksum_algorithm = 'sha-256'),
  checksum_hex TEXT NOT NULL CHECK (checksum_hex ~ '^[0-9a-f]{64}$')
);
`,
  }),
  Object.freeze({
    id: "0002-evaluation-run-aggregate",
    content: `
ALTER TABLE aggregates DROP CONSTRAINT aggregates_aggregate_type_check;
ALTER TABLE aggregates ADD CONSTRAINT aggregates_aggregate_type_check
  CHECK (aggregate_type IN ('artifact-manifest','budget-account','evaluation-run','project','product-plan','task-graph','task-run','telemetry-ledger','worker-run'));

ALTER TABLE events DROP CONSTRAINT events_aggregate_type_check;
ALTER TABLE events ADD CONSTRAINT events_aggregate_type_check
  CHECK (aggregate_type IN ('artifact-manifest','budget-account','evaluation-run','project','product-plan','task-graph','task-run','telemetry-ledger','worker-run'));
`,
  }),
  Object.freeze({
    id: "0003-integration-run-aggregate",
    content: `
ALTER TABLE aggregates DROP CONSTRAINT aggregates_aggregate_type_check;
ALTER TABLE aggregates ADD CONSTRAINT aggregates_aggregate_type_check
  CHECK (aggregate_type IN ('artifact-manifest','budget-account','evaluation-run','integration-run','project','product-plan','task-graph','task-run','telemetry-ledger','worker-run'));

ALTER TABLE events DROP CONSTRAINT events_aggregate_type_check;
ALTER TABLE events ADD CONSTRAINT events_aggregate_type_check
  CHECK (aggregate_type IN ('artifact-manifest','budget-account','evaluation-run','integration-run','project','product-plan','task-graph','task-run','telemetry-ledger','worker-run'));
`,
  }),
]);

const MIGRATION_LOCK_NAMESPACE = 1_092_874_307;
const MIGRATION_LOCK_KEY = 324_018_522;

function quoteIdentifier(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`;
}

function safeSqlState(error: unknown): string | null {
  if (typeof error !== "object" || error === null || !("code" in error)) {
    return null;
  }
  const value = (error as { readonly code?: unknown }).code;
  return typeof value === "string" && /^[0-9A-Z]{5}$/.test(value) ? value : null;
}

function migrationFailure(error: unknown, migrationId: string): PersistenceError {
  if (error instanceof PersistenceError) {
    return error;
  }
  return new PersistenceError("MIGRATION_FAILED", "A PostgreSQL schema migration failed to apply.", {
    migrationId,
    postgresCode: safeSqlState(error),
  });
}

async function readAppliedMigrations(
  client: DatabaseClient,
  schema: string,
  maximumRows: number,
): Promise<readonly AppliedMigration[]> {
  const result = await client.query(
    `SELECT id, checksum_algorithm, checksum_hex, applied_at, ordinal::text AS ordinal
       FROM ${quoteIdentifier(schema)}.schema_migrations ORDER BY ordinal ASC LIMIT $1`,
    [maximumRows],
  );
  return Object.freeze(
    result.rows.map((row, index) =>
      parseAppliedMigration(
        {
          id: row["id"],
          checksum: {
            algorithm: row["checksum_algorithm"],
            hex: row["checksum_hex"],
          },
          appliedAt: row["applied_at"],
          ordinal: typeof row["ordinal"] === "string" ? Number(row["ordinal"]) : row["ordinal"],
        },
        `appliedMigrations[${index}]`,
      ),
    ),
  );
}

async function setLocalSearchPath(client: DatabaseClient, schema: string): Promise<void> {
  await client.query(`SET LOCAL search_path TO ${quoteIdentifier(schema)}, pg_catalog`);
}

export async function migrationStatus(
  pool: DatabasePool,
  schema: string,
  definitions: readonly MigrationDefinition[] = POSTGRES_MIGRATIONS,
): Promise<MigrationStatus> {
  void planMigrations(definitions, []);
  const client = await pool.connect();
  try {
    return planMigrations(
      definitions,
      await readAppliedMigrations(client, schema, definitions.length + 1),
    ).status;
  } finally {
    client.release();
  }
}

/** Serializes startup, validates exact history, and commits each forward migration independently. */
export async function applyPostgresMigrations(
  pool: DatabasePool,
  schema: string,
  clock: Clock,
  definitions: readonly MigrationDefinition[] = POSTGRES_MIGRATIONS,
): Promise<MigrationStatus> {
  void planMigrations(definitions, []);
  const client = await pool.connect();
  let destroy = false;
  try {
    await client.query("SELECT pg_catalog.pg_advisory_lock($1, $2)", [
      MIGRATION_LOCK_NAMESPACE,
      MIGRATION_LOCK_KEY,
    ]);
    await client.query(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(schema)}`);
    await client.query(`CREATE TABLE IF NOT EXISTS ${quoteIdentifier(schema)}.schema_migrations (
      id TEXT COLLATE "C" PRIMARY KEY,
      checksum_algorithm TEXT NOT NULL,
      checksum_hex TEXT NOT NULL,
      applied_at TEXT NOT NULL,
      ordinal BIGINT NOT NULL UNIQUE
    )`);

    const applied = await readAppliedMigrations(client, schema, definitions.length + 1);
    const plan = planMigrations(definitions, applied);
    let ordinal = applied.length;
    for (const definition of plan.toApply) {
      ordinal += 1;
      await client.query("BEGIN");
      try {
        await setLocalSearchPath(client, schema);
        await client.query(definition.content);
        const checksum = migrationChecksum(definition);
        await client.query(
          `INSERT INTO ${quoteIdentifier(schema)}.schema_migrations
             (id, checksum_algorithm, checksum_hex, applied_at, ordinal)
           VALUES ($1, $2, $3, $4, $5)`,
          [definition.id, checksum.algorithm, checksum.hex, clock.now().toISOString(), ordinal],
        );
        await client.query("COMMIT");
      } catch (error) {
        try {
          await client.query("ROLLBACK");
        } catch {
          destroy = true;
        }
        throw migrationFailure(error, definition.id);
      }
    }
    return planMigrations(
      definitions,
      await readAppliedMigrations(client, schema, definitions.length + 1),
    ).status;
  } catch (error) {
    if (error instanceof PersistenceError) {
      throw error;
    }
    throw migrationFailure(error, "0000-bootstrap");
  } finally {
    if (!destroy) {
      try {
        await client.query("SELECT pg_catalog.pg_advisory_unlock($1, $2)", [
          MIGRATION_LOCK_NAMESPACE,
          MIGRATION_LOCK_KEY,
        ]);
      } catch {
        destroy = true;
      }
    }
    client.release(destroy);
  }
}

export const postgresMigrationTesting = Object.freeze({
  applyPostgresMigrations,
  migrationStatus,
  quoteIdentifier,
  safeSqlState,
});
