import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { migrationChecksum } from "@ai-dev-os/persistence";
import { POSTGRES_MIGRATIONS } from "../src/index.js";

const packageRoot = resolve(import.meta.dirname, "..");

function read(path: string): string {
  return readFileSync(path, "utf8");
}

function sources(directory: string): readonly string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory()
      ? sources(path)
      : entry.isFile() && entry.name.endsWith(".ts")
        ? [read(path)]
        : [];
  });
}

describe("PostgreSQL package static policy", () => {
  it("has no ambient credential/configuration path or logging authority", () => {
    const source = sources(resolve(packageRoot, "src")).join("\n");
    for (const forbidden of [
      "process.env",
      "connectionString",
      "console.log",
      "console.error",
      "pg-native",
      "error.message",
      "error.detail",
      "error.hint",
      "error.query",
    ]) {
      expect(source).not.toContain(forbidden);
    }
  });

  it("pins the native locking, sequence, checksum, and migration invariants", () => {
    expect(POSTGRES_MIGRATIONS).toHaveLength(1);
    const migration = POSTGRES_MIGRATIONS[0];
    expect(migration?.id).toBe("0001-initial-schema");
    expect(migrationChecksum(migration!).hex).toBe(
      "34413d60368bc485b1cbdc088d5000baa4ce31829c71ff0947d813aae1545f11",
    );
    const adapter = read(resolve(packageRoot, "src", "postgres-adapter.ts"));
    const migrations = read(resolve(packageRoot, "src", "migrations.ts"));
    expect(adapter).toContain("FOR UPDATE SKIP LOCKED");
    expect(adapter).toContain("pg_advisory_xact_lock");
    expect(adapter).toContain("BEGIN ISOLATION LEVEL SERIALIZABLE");
    expect(adapter).toContain("ON CONFLICT (aggregate_type, aggregate_id) DO NOTHING");
    expect(migrations).toContain("pg_advisory_lock");
    expect(migrations).toContain("ORDER BY ordinal ASC LIMIT $1");
    expect(migrations).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(migrations).toContain("COLLATE \"C\"");
  });

  it("publishes only reviewed files and the direct pure-JavaScript driver stack", () => {
    const manifest = JSON.parse(read(resolve(packageRoot, "package.json"))) as {
      readonly dependencies: Record<string, string>;
      readonly devDependencies: Record<string, string>;
      readonly files: readonly string[];
      readonly exports: Record<string, unknown>;
      readonly scripts: Record<string, string>;
    };
    expect(manifest.dependencies).toEqual({
      "@ai-dev-os/artifacts": "^0.1.0",
      "@ai-dev-os/domain": "^0.1.0",
      "@ai-dev-os/persistence": "^0.1.0",
      pg: "8.23.0",
      "pg-pool": "3.14.0",
    });
    expect(manifest.devDependencies).toEqual({ "@types/pg": "8.21.0" });
    expect(manifest.files).toEqual(["dist", "README.md"]);
    expect(Object.keys(manifest.exports).sort()).toEqual([".", "./testing"]);
    expect(manifest.scripts["pretest"]).toBe("npm run build");
    expect(manifest.scripts["pretest:live"]).toBe("npm run build");
    expect(manifest.scripts["pretest:coverage"]).toBe("npm run build");

    const pgManifest = JSON.parse(read(resolve(packageRoot, "..", "..", "node_modules", "pg", "package.json"))) as {
      readonly version: string;
      readonly license: string;
      readonly scripts?: Record<string, string>;
    };
    expect(pgManifest).toMatchObject({ version: "8.23.0", license: "MIT" });
    expect(pgManifest.scripts?.["install"]).toBeUndefined();
    expect(pgManifest.scripts?.["preinstall"]).toBeUndefined();
    expect(pgManifest.scripts?.["postinstall"]).toBeUndefined();
  });
});
